### ISSUE TITLE
Errors with namespaces and self-closing tags

### ISSUE THREAD

**Issue by rubennorte** [callumlocke/soup#2]
I don't know if there's support for namespaces and self-closing tags, but Soup isn't working properly with them.

With this code:

```javascript
var soup = new Soup(htmlContent);
soup.setAttribute('[attr]', 'attr', function(oldValue) {
  return oldValue + '?t=now';
});
soup.toString();
```

When htmlContent is:

```html
<some:namespace attr="value">
<element attr="other-value">
```

* Expected output:

  ```html
  <some:namespace attr="value?t=now">
  <element attr="other-value?t=now">
  ```

* Actual output:

  ```html
  <some:namespace attr="value?t=now">
  <element attr="other-value?t=nowother-valueother-value?t=now">
  ```

When htmlContent is:

```html
<other attr="value" />
<element attr="other-value">
```

* Expected output:

  ```html
  <other attr="value?t=now" />
  <element attr="other-value?t=now">
  ```

* Actual output:

  ```html
  <other attr="value?t=now" />
  <element attr="other-value?t=nowother-valueother-value?t=now">
```

It'd be nice to have support for them. If that's not possible, could you specify it in the docs?

**Comment by callumlocke** [comment]
interesting, thanks for the report. yes these should be supported.

what's the problem with the namespaced one? I can't see any difference between your actual and expected, for the namespaced element.

I'm looking into the other one...

**Comment by rubennorte** [comment]
The namespaced tag is fine in the output, but it's what's causing the error in the next tag. It's the same as in the other example (the first tag is causing the error in the next one).

**Comment by callumlocke** [comment]
This bug is really weird. It seems to only happen under very specific conditions, and one of the conditions is that the attribute's name is actually "attr". If I change it to "foo" or anything else, the bug doesn't occur. 

Can you confirm this? Can you make this bug occur with any other attribute name, other than "attr"?

**Comment by rubennorte** [comment]
Yes, it also happens when the attribute is "src", in the same conditions.

**Comment by rubennorte** [comment]
I'm closing this after a year because I see the package is no longer maintained and I don't use it anymore.

**Comment by bigmeow** [comment]
@rubennorte Do you have other alternative npm packages
